### ISSUE TITLE
I can't run zefyr in flutter web

### ISSUE THREAD

**Issue by Lykeosovandara** [memspace/zefyr#110]
## Steps to Reproduce

1. ... I can't install in flutter web project
2. ...
3. ...

## Logs

```
Resolving dependencies...
Because zefyr >=0.1.2 depends on flutter any from sdk which is forbidden, zefyr >=0.1.2 is forbidden.
So, because login_page depends on zefyr ^0.5.0, version solving failed.
```

**Comment by NicolasDionB** [comment]
Flutter web does not support plugins yet. When it does, the plugin is going to have to support web as well (ie: updated plugin)...

**Comment by pulyaevskiy** [comment]
I will be looking at the state of Flutter Web. The main thing we need there is TextInputPlugin, which comes with the SDK and might already be supported. However there could be other potential issues since I have no idea if Flutter for Web decided to reimplement input fields the same way they do for Android/iOS. In short, if Flutter for Web works the same for input fields then everything might "just work". 

However if they decided to leverage browser's `<input>` fields, then things may get tricky.

**Comment by pulyaevskiy** [comment]
Apparently Flutter Gallery is available in Web version now.

Looking at the Text Fields demo I'm fairly sure Flutter for Web renders its own input fields instead of using HTML `<input>` which is good news!

![image](https://user-images.githubusercontent.com/441756/58343112-21e46d80-7e07-11e9-8f92-257960a70183.png)

**Comment by NicolasDionB** [comment]
That's promising. Looks like they are doing things properly, that's good and looking better for plugins migration.

**Comment by daracodecourse** [comment]
Cool do you know when flutter web support plugins?

**Comment by NicolasDionB** [comment]
I know they are merging with the main flutter SDK right now and as far as I can tell from the milestones, it should be done by June? Fingers crossed!

**Comment by ciokan** [comment]
> I know they are merging with the main flutter SDK right now and as far as I can tell from the milestones, it should be done by June? Fingers crossed!

That means this package will just work when they merge with the `flutter` sdk instead of `flutter_web` right?

**Comment by NicolasDionB** [comment]
Hopefully, that is depending of the implementation they do for TextInputPlugin as @pulyaevskiy said.

**Comment by deisold** [comment]
Hi, I'm also getting compile erros in a Flutter web app with zefyr: ^0.8.0.

Anyone an idea?

============================================

Error creating |lib/main.ddc.dill
Error creating kernel summary for module:xxxxxxxxx|lib/main.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/xxxxxxxxx/main.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_iAMieI/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_SX1cni/used_inputs.txt --input-summary=org-dartlang-app:///packages/kiwi/kiwi.ddc.dill --input-summary=org-dartlang-app:///packages/provider/provider.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/logging/logging.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/auto_size_text/auto_size_text.ddc.dill --input-summary=org-dartlang-app:///packages/marquee/marquee.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/util.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/src/fast_diff.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:xxxxxxxxx/main.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.


Error creating xxxxxxxxx|lib/view/common/subscribeBar/SubscribeBar.ddc.dill
Error creating kernel summary for module:xxxxxxxxx|lib/view/common/subscribeBar/SubscribeBar.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/xxxxxxxxx/view/common/subscribeBar/SubscribeBar.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_qIKrXs/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_oZkzd0/used_inputs.txt --input-summary=org-dartlang-app:///packages/kiwi/kiwi.ddc.dill --input-summary=org-dartlang-app:///packages/provider/provider.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/logging/logging.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/auto_size_text/auto_size_text.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/util.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/src/fast_diff.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:xxxxxxxxx/view/common/subscribeBar/SubscribeBar.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.


Error creating xxxxxxxxx|lib/di/injector.ddc.dill
Error creating kernel summary for module:xxxxxxxxx|lib/di/injector.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/xxxxxxxxx/di/injector.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_zHgUNh/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_dXalPD/used_inputs.txt --input-summary=org-dartlang-app:///packages/kiwi/kiwi.ddc.dill --input-summary=org-dartlang-app:///packages/provider/provider.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/logging/logging.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/auto_size_text/auto_size_text.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/util.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/src/fast_diff.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:xxxxxxxxx/view.dart --source=package:xxxxxxxxx/viewModel.dart --source=package:xxxxxxxxx/view/common/navigation.dart --source=package:xxxxxxxxx/di/injector.dart --source=package:xxxxxxxxx/view2Model.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.



AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill
Error creating xxxxxxxxx|lib/view2.ddc.dill
Error creating kernel summary for module:xxxxxxxxx|lib/view2.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/xxxxxxxxx/view2.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_mDchsU/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_IE1Eeo/used_inputs.txt --input-summary=org-dartlang-app:///packages/kiwi/kiwi.ddc.dill --input-summary=org-dartlang-app:///packages/provider/provider.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/logging/logging.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/auto_size_text/auto_size_text.ddc.dill --input-summary=org-dartlang-app:///packages/marquee/marquee.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/util.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/src/fast_diff.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:xxxxxxxxx/view2.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.



AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill

AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill

AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill

AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill

AssetNotFoundException: xxxxxxxxx|lib/main_web_entrypoint.ddc.js
Error creating xxxxxxxxx|lib/view/common/AppRichEditor.ddc.dill
Error creating kernel summary for module:xxxxxxxxx|lib/view/common/AppRichEditor.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/xxxxxxxxx/view/common/AppRichEditor.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_7hp0QY/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_M9muSE/used_inputs.txt --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/util.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/zefyr/src/fast_diff.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:xxxxxxxxx/view/common/AppRichEditor.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.



AssetNotFoundException: zefyr|lib/src/widgets/buttons.ddc.dill
Error creating zefyr|lib/src/widgets/buttons.ddc.dill
Error creating kernel summary for module:zefyr|lib/src/widgets/buttons.ddc.dill

Response:--dart-sdk-summary=file:///Users/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --output=/private/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/scratch_spaceFfiaXs/packages/zefyr/src/widgets/buttons.ddc.dill --packages-file=file:///var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_3nUk7Z/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/tv/pkrm9t0d3y389c84s_c0wvjh0000gn/T/kernel_builder_p6STed/used_inputs.txt --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher/url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/notus/notus.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/quiver_hashcode/hashcode.ddc.dill --input-summary=org-dartlang-app:///packages/quill_delta/quill_delta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/url_launcher_platform_interface/method_channel_url_launcher.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/notus/src/document/attributes.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --source=package:zefyr/src/widgets/caret.dart --source=package:zefyr/src/widgets/editor.dart --source=package:zefyr/src/widgets/rich_text.dart --source=package:zefyr/src/widgets/horizontal_rule.dart --source=package:zefyr/src/widgets/toolbar.dart --source=package:zefyr/src/widgets/input.dart --source=package:zefyr/src/widgets/render_context.dart --source=package:zefyr/src/widgets/quote.dart --source=package:zefyr/src/widgets/common.dart --source=package:zefyr/src/widgets/selection.dart --source=package:zefyr/src/widgets/controller.dart --source=package:zefyr/src/widgets/editable_box.dart --source=package:zefyr/src/widgets/code.dart --source=package:zefyr/src/widgets/list.dart --source=package:zefyr/src/widgets/paragraph.dart --source=package:zefyr/src/widgets/buttons.dart --source=package:zefyr/src/widgets/editable_text.dart --source=package:zefyr/src/widgets/cursor_timer.dart --source=package:zefyr/src/widgets/mode.dart --source=package:zefyr/src/widgets/field.dart --source=package:zefyr/src/widgets/scaffold.dart --source=package:zefyr/src/widgets/image.dart --source=package:zefyr/src/widgets/scope.dart --source=package:zefyr/zefyr.dart --source=package:zefyr/src/widgets/theme.dart --source=package:zefyr/src/widgets/view.dart
org-dartlang-app:///packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.


Error compiling dartdevc module:zefyr|lib/src/widgets/buttons.ddc.js

packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
packages/flutter/src/services/text_input.dart: Context: 'TextInputClient.connectionClosed' is defined here.


Failed after 255ms
Finished with error: Failed to build application for the Web.

**Comment by cgestes** [comment]
#206 needs to be merged and released.

use https://github.com/memspace/zefyr/tree/fix-text-input-connection-closed in the meantime.

**Comment by deisold** [comment]
Thanks @cgestes, do you know how to declare the dependency to that repo?

This didn't work:

zefyr:
    git:
      url: git@github.com:memspace/zefyr.git

**Comment by deisold** [comment]
Thanks @cgestes,

I imported this fix as:

  zefyr:
    git:
      url: git@github.com:memspace/zefyr.git
      path: packages/zefyr

and I'm getting the same error.

Is the import wrong?

**Comment by cgestes** [comment]
you need to use this branch: https://github.com/memspace/zefyr/tree/fix-text-input-connection-closed

**Comment by deisold** [comment]
I got it compiled and run, but there are several issues/bug which makes it not usable for web.

**Comment by nelsonic** [comment]
Greetings Zefyr Devs! 👋 
7 months have passed since the last comment on this thread, has there been any progress?

Op pub.dev it says Web is supported: https://pub.dev/flutter/packages?q=zefyr&platform=web
<img width="937" alt="zefyr-pub-dev-web-supported" src="https://user-images.githubusercontent.com/194400/83515623-95ff2a00-a4cd-11ea-878d-8bb78c9e2de5.png">

We have not been able to find any docs or examples for web support. 

The release notes in the GitBook say `0.8.0` is the _Current_ version:
https://zefyr-editor.gitbook.io/docs/release-notes
![image](https://user-images.githubusercontent.com/194400/83515388-31dc6600-a4cd-11ea-9127-66556fb7d2c9.png)

But pub.dev has `0.11.0` updated May 15, 2020. 
(_guessing that's the right version and the GitBook is just behind_) 

Totally understand that "***Zefyr is currently in early preview***." ...
We are just trying to determine if we can start _using_ it in an App we are developing.
We ideally want the App to run on Web (first), then iOS and Android (and eventually Desktop). 
Has anyone been able to get Zefyr working for a Flutter Web App?
Thanks! ☀️

**Comment by nelsonic** [comment]
Most recent issue addressing Web support appears to be: https://github.com/memspace/zefyr/issues/333 💭

**Comment by pulyaevskiy** [comment]
This is addressed in the 1.0-dev branch, please see https://github.com/memspace/zefyr/issues/409 for details about 1.0.
Closing this but note that Web support is very limited right now and is lacking a few key features. This is partly due to the Flutter for Web itself lacking support for some aspect of rich text rendering.

**Comment by WillCanU** [comment]
> This is addressed in the 1.0-dev branch, please see #409 for details about 1.0.
> Closing this but note that Web support is very limited right now and is lacking a few key features. This is partly due to the Flutter for Web itself lacking support for some aspect of rich text rendering.

@pulyaevskiy From my investigation there seemed to be an issue with the selection not calling on _getPositionForOffset in Text.dart when using RichText. Do you know of any open issues where this is being tracked?

**Comment by cgestes** [comment]
Have a look here: https://github.com/flutter/flutter/issues/33523

**Comment by WillCanU** [comment]
> Have a look here: [flutter/flutter#33523](https://github.com/flutter/flutter/issues/33523)
I believe canvas-based text is enabled at-least in Master. I've tested with the flag enabled and in beta, dev & master and It's still reproducible.

**Comment by pulyaevskiy** [comment]
If there is a particular bug related to Web support in Zefyr, please submit a new issue. Otherwise it gets hard to follow the conversation.

In regards to your discovery @WillCanU please 👍 this issue https://github.com/flutter/flutter/issues/55587 which is about adding proper metrics measurements for rich text. AFAIK this is the reason for things being broken in regards to showing selection and moving the cursor - these rely on text metrics.

(I'm going to lock this thread, but feel free to submit a dedicated issue re: this bug if you'd like to continue the conversation).
